### ISSUE TITLE
Automation Script not working - installArcAgentSQL.ps1 - https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/

### ISSUE THREAD

**Issue by WVDAdminTF** [microsoft/azure_arc#1394]
The below task is not functional
[installArcAgentSQL.ps1](https://github.com/microsoft/azure_arc/blob/main/azure_arc_sqlsrv_jumpstart/azure/arm_template/scripts/installArcAgentSQL.ps1) - This is the main script and will be executed by the LogonScript script at VM runtime. This script has the following functionalities:

Project SQL Server as an Azure Arc-enabled SQL server resource

**Error**
Installing Az.connectedMachine module.
INFO: Loaded Module 'Az.MSGraph'
INFO: Loaded Module 'Az.Accounts'
INFO: Loaded Module 'Az.Authorization'
**WARNING: User does not have permissions to assign roles. This is pre-requisite to on board SQL Server - Azure Arc resources.**

PS>$global:?
True

**Comment by DCMattyG** [comment]
Hello @WVDAdminTF, can you please confirm what IAM role your Service Principal has for the target subscription you're deploying this Jumpstart scenario into?

**Comment by WVDAdminTF** [comment]
> can you please confirm what IAM role your Service Principal has for th

Yes, I am following the guide and using the Service Principal created using below command's Output
az login
subscriptionId=$(az account show --query id --output tsv)
az ad sp create-for-rbac -n "JumpstartArc" --role "**Contributor**" --scopes /subscriptions/$subscriptionId

{
"appId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"displayName": "JumpstartArc",
"password": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"tenant": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}

So does it need more permission that the above, if so please advise and also please have the guide updated with the same.

**Comment by DCMattyG** [comment]
Hi @WVDAdminTF, I've done some testing and will be updating the requirements to have the Service Principal be an "Owner" of the target subscription. This is because the Arc-enabled SQL onboarding process requires the ability to change RBAC permissions on some objects. At a minimum it would need to be an "Contributor" at the subscription level, and an "Owner" at the Resource Group level.

I'll also be tweaking the onboarding script we use to reflect some improvements we made in ArcBox around this process.

You'll see a PR pushed soon for this. thanks so much for reporting this and sharing the helpful details!
