### ISSUE TITLE
Jumpstart HCIBox - hardcoded azure location for registration

### ISSUE THREAD

**Issue by jjindrich** [microsoft/azure_arc#1474]
There is hardcoded Azure Region when you are creating new resource group for Azure Arc HCI 
$azureLocation = 'eastus'
line 45 in Register-AzSHCI.ps1

It fails if you have limited allowed regions !

**Comment by dkirby-ms** [comment]
Thank you, @jjindrich. The reason we hardcoded it this way is because the regions where the cluster can be registered are limited to a select group. https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#region-availability

We are exploring ways to make this configurable by the user so they can select a region that is preferable from the available options. 

I will add a note to the documentation explaining the hardcoded eastus value so that users are aware of this.
