### ISSUE TITLE
Timed out installing Arc for Server Agent:  The operation has timed out

### ISSUE THREAD

**Issue by malcatraz** [microsoft/azure_arc#1523]
**A link to the Jumpstart scenario you are working on.**
(https://azurearcjumpstart.io/azure_jumpstart_hcibox/rb/)

**Describe the bug.**
While deploying a VM in the HCIBox-Cluster I receive the following error message.  
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"Timed out installing ArcForServerAgent: The operation has timed out"}]} HCI

**To Reproduce.**
1. Go to HCIBox-VCluster
2. Click on Virtual Machines
3. Go to Virtual Machines under Resources'
4. Select to create a VM and use Windows Server 2022 image. 

**Expected behavior.**
a Virtual machine should be provisioned without error.  

**Environment summary.**

**Screenshots.**
![image](https://user-images.githubusercontent.com/32576278/201363842-4771a271-34ed-4f29-8ae5-4949e57e02d1.png)

**Additional context.**

**Comment by mgodfre3** [comment]
Malcolm in 1522 you say you can't get the server 2022 image down from the marketplace but in this error you are using that image to deploy a vm and it's timing out on arc?  This seems odd since you couldn't get the image. Also this shows that the vm didn't pick up an ip address. Can you confirm if your vm is using Apipa or an assigned ip from the vnet scope?

**Comment by dkirby-ms** [comment]
This is caused because there is a known issue with timeouts when onboarding a VM with guest management enabled. To workaround it, when creating the VM from Azure portal, leave the "enable guest management" box unchecked.
