### ISSUE TITLE
Large number of Evicted pods after restart (Jump start data services with microk8s and Postgres)

### ISSUE THREAD

**Issue by basimolimajeed** [microsoft/azure_arc#1586]
(https://github.com/microsoft/azure_arc/tree/main/azure_arc_data_jumpstart/microk8s)

**Describe the bug**
After restarting the microk8s node vm , I notice a large number of pods with Status=Evicted or ContainerStatusUnknown

**To Reproduce**
1. Install the jump start (works successfully)
2. Restart the Azure VM with the microk8s node 
3. examine the pods
4. Screenshots attached to show the view I get

**Expected behavior**
 should there be so many Evicted or unknows status pods ? will that impact the node resources?

**Environment summary**
Jumpstart set up

**Screenshots**
![image](https://user-images.githubusercontent.com/16608331/210056453-fbd90fae-698c-4410-b7b6-dc0faf4887b1.png)

![image](https://user-images.githubusercontent.com/16608331/210056509-3bd0fc4c-2579-4244-9de7-5502ef3690dd.png)

**Comment by likamrat** [comment]
Adding @brndoko from the team for addtional information.

**Comment by mdrakiburrahman** [comment]
Hey @basimolimajeed, so I don't think this is a "Jumpstart" or "Data Services" not working problem, it's a "Microk8s" and "Kubernetes" not working problem.

Because Jumpstart sets up a single-node K8s (the `master` node - hosting APIServer, and `worker` node hosting "stuff") all run in a single Ubuntu VM, when you went ahead and restarted that single Ubuntu VM, Kubernetes became confused when it restarted, because APIServer went down. This confusion leads to evictions because APIServer is down, or perhaps `etcd` is having issues (we can't tell from your screenshot, but you can check the APIServer logs why it's reporting bad status).

Kubernetes, as a system, specially `etcd` and `apiserver` is not designed to _completely_ go down. This is why in real life, organizations run multi-master setups (so that the brains, `etcd` and `apiserver`, is always running with at least a single replica). This is also the case in AKS, GKE, EKS etc., where the master nodes are "cloud managed", and cannot be restarted manually - so you cannot get yourself in a situation like this. Microk8s obviously cannot protect itself like this.

Since the Jumpstart Microk8s is just for demo, it runs a single Ubuntu VM. The scenario is never really meant to be _"turned off, restarted, and everything is good"_ - Jumpstart cannot guarantee that, nor can single-node microk8s.  - if end-users restart the single Microk8s node, YMMV because Kubernetes struggles to reschedule both "brain" pods and "workload" pods (as we can see from the screenshot).

We know this isn't a Data Services or even a Jumpstart problem, because in your screenshot, we see Kubernetes pods in `Unknown` status, so we know - this is a "Kubernetes" bug, or at least, a Microk8s bug:
![image](https://user-images.githubusercontent.com/46581776/210666895-84de1034-a5db-4b2f-aa53-2e6e3c99e7f0.png)

Microk8s has a multi-master setup. but Jumpstart doesn't use it (it would be expensive):
https://microk8s.io/docs/high-availability

I think we can document in the J

**Comment by basimolimajeed** [comment]
Thank you @mdrakiburrahman for clarifying. The single node set up could be the reason as you suggested. 

But I tried the set up without relying on the jumpstart scripts (one single microk8s node, arc data controller and postgresql node), and when I restarted the node there were no evicted pods. However I noticed that after restart the controldb pod does not start and I have to delete it then it gets recreated and starts working. In any case this is not a jumpstart issue.

Regards

Basim

**Comment by mdrakiburrahman** [comment]
I'm guessing you did this on your laptop? So basically, Kubernetes' core operators (the `StatefulSet` scheduler - it is the brain behind scheduling `controldb`) is not bulletproof, specially when you run minified version of Kubernetes like Microk8s. I don't think it's documented anywhere, but speaking from personal experience (I've been running Microk8s on my home desktop for the last 3 years), when you restart the underlying Ubuntu VM that has Microk8s, unexpected things happen, like `etcd` running into quorum problems. 

You either need to be a bit of a Kubernetes expert to recover from these problems, or follow the rule-of-thumb to run highly available `master` nodes, or never restart Kubernetes.

**Comment by mdrakiburrahman** [comment]
@likamrat I think we're good to close the bug at this point and document the end-user warning that restarting the single-node Microk8s can lead to weird end-user experiences because Kubernetes itself can fail to recover stability after downtime

**Comment by basimolimajeed** [comment]
Happy to close it @mdrakiburrahman , I understand your view. I am running on Azure VMs by the way. In the future I will try with multi master set up.
Thanks

**Comment by mdrakiburrahman** [comment]
@basimolimajeed - absolutely!

Small tip - if this is your first time trying to get used to Arc Data Services - and you're not a Kubernetes expert (yet), I'd personally recommend playing around on a managed, "premium" Kubernetes offering like AKS, rather than Microk8s. Because AKS will not present you with these weird problems because the back-end infra is well protected.

The reason being, what you're seeing right now, is "Microk8s's" problems intermingled with Arc Data Services, and this is leading you to have some confusions (like `controldb` not "working").

Once you've familiarized with the expected behavior, then once you move to self-managed K8s like Microk8s, you'll figure out the patterns to recover things quickly.

Cheers!
