### ISSUE TITLE
Support for Rocky Linux 9

### ISSUE THREAD

**Issue by y0rune** [microsoft/azure_arc#1751]
Hello!
We would like to install the Azure Arc in the Rocky Linux 9. I found out that the repo for RHEL 9 is working. 
In the file `https://aka.ms/azcmagent` I added the new `if` and that's working fine.
```diff
diff --git a/installationScripts b/installationScripts
index b6ef2e2..3d9ed3e 100644
--- a/installationScripts
+++ b/installationScripts
@@ -391,6 +391,9 @@ case "${distro}" in
         if [ "${distro_major_version}" -eq 8 ]; then
             echo "Configuring for Rocky Linux 8..."
             rpm_distro=rhel/8
+        elif [ "${distro_major_version}" -eq 9 ]; then
+            echo "Configuring for Rocky Linux 9..."
+            rpm_distro=rhel/9.0
         else
             exit_failure 133 "$0: unsupported Linux distribution: ${distro}:${distro_major_version}.${distro_minor_version}. For supported OSs, see https://learn.microsoft.com/en-us/azure/azure-arc/servers/prerequisites#supported-operating-systems"
         fi
```

I wanted to create the PR for it but I did not find that file here :C 

Thank you!

**Comment by rpsqrd** [comment]
We have not tested our agent on RL9 and, therefore, do not officially support it. It's in our backlog, but I don't have an ETA to share at this time. However, as you noted, it likely works since we do support RHEL9.

For future reference, the best place to make feature requests for Azure Arc is here: https://feedback.azure.com/d365community/forum/5c778dec-0625-ec11-b6e6-000d3a4f0858

**Comment by y0rune** [comment]
Thank for the answer!
Have a great weekend ;)
