### ISSUE TITLE
DNS resolvements don't match up

### ISSUE THREAD

**Issue by dsfrederic** [microsoft/azure_arc#1759]
**Is your issue related to a Jumpstart scenario, ArcBox, or HCIBox?**

Yes, Azure ARC AKS Edge node. 

**Describe the bug**

DNS Resolvement works on node but not in pod

**To Reproduce**
See screenshot for commands

**Expected behavior**
DNS resolvement is same as in the pod

**Environment summary**
NA

**Have you looked at the Troubleshooting and Logs section?**
Yes

**Screenshots**

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/28486949/228766024-d6f795b3-07e9-49a1-b67d-fd64ec6a7597.png">

**Additional context**
i'm trying to run ADF SHIR container (windows)

**Comment by likamrat** [comment]
@dsfrederic it does not look you are working a Jumpstart scenario. Issues in this repo are related to Jumpstart content, not product support.

**Comment by likamrat** [comment]
Can you please share he logs as decribed in the README?

**Comment by dsfrederic** [comment]
@pabloameijeirascanay that seems to work 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/28486949/229518340-5f3d5892-d1bd-4148-97b3-0f7a6043f3eb.png">

**Comment by pabloameijeirascanay** [comment]
Hi @dsfrederic, it is a Windows VM bug.

![image](https://user-images.githubusercontent.com/87183849/229710754-1db3fdfd-1a9e-4633-9e78-524af6f78505.png)

The Windows VM host OS has access to internet, but we don't see that 10.X network inside the Windows VM.

We have scaled it internally to the AKS Edge Essentials product team, thank you for opening the issue. We will update the issue when a new version fixing the bug is released.

**Comment by dsfrederic** [comment]
Do you have a workaround for this? @pabloameijeirascanay

**Comment by likamrat** [comment]
@dsfrederic this issue is now solved as part of the [latest AKS EE release](https://github.com/Azure/AKS-Edge/releases/tag/1.2.414.0). Please feel free to comment if you see the issue still persists. /cc @fcabrera23 
Closing for now.
