### ISSUE TITLE
HCIBox: 23H2 not supported

### ISSUE THREAD

**Issue by fberson** [microsoft/azure_arc#2304]
I have deployed the Jumpstart HCI box. The deployment itself was successful, and the bridge and custom locations were created, but the 2 VM images, as well as any additional marketplace image I try to add, show the error below. I've seen previous comments here that the HCIBox experience is being updated to support 23H2. Is that the cause of this error, and is there any timeline for the Jumpstart HCI box to work again? @dkirby-ms 

{
  "error": {
    "code": "NotSupported",
    "message": "Supported OS Versions : 23H2 or higher. Node(s) not supported : AzSHOST1,AzSHOST2. : Not Supported"
  }
}

![image](https://github.com/microsoft/azure_arc/assets/10365958/99c38c2a-de81-4498-b055-4e37f8d0c434)

**Comment by avooca** [comment]
Same issue here with a fresh deployment today.  Side note: i could not deploy an HCI Box due to #2199 until I re-cloned the repo today; I had been getting stuck with a clone from Ignite + 1 day.  Maybe can give the author a hint of when this broke :)

{"code":"NotSupported","message":"Supported OS Versions : 23H2 or higher. Node(s) not supported : AzSHOST2,AzSHOST1. : Not Supported"}

**Comment by dkirby-ms** [comment]
Good catch, and yes this is related to the HCI 23h2 preview release from a couple weeks back. I updated the HCIBox 2.0 discussion thread with some more details on work to support 23h2 in HCIBox. See here - https://github.com/microsoft/azure_arc/discussions/1454

**Comment by fberson** [comment]
@dkirby-ms, is there any news on this?

**Comment by dkirby-ms** [comment]
Hi @fberson,

I have seen repeated validation errors when deploying with the current 2310 build of AzSHCI. I was advised to wait until the 2311 release (which should be coming in the next few days) to have the validation issues resolved. Otherwise, the hcibox_23h2 branch I have in my fork is ready to go with the updates for 23h2 along with a number of other code revisions.

**Comment by fberson** [comment]
Thanks @dkirby-ms, does that mean we can expect an updated version of the Jumpstart HCI box in a few days as well that fixes the issues above?

**Comment by dkirby-ms** [comment]
> Thanks @dkirby-ms, does that mean we can expect an updated version of the Jumpstart HCI box in a few days as well that fixes the issues above?

No ETA yet. I am still seeing issues in the deployment process post-validation. There was also a recent HCI RP API update that I am reviewing as well.

**Comment by fberson** [comment]
@dkirby-ms, any news yet when we can expect the Jumpstart HCI to work again? Thanks!

**Comment by dkirby-ms** [comment]
> @dkirby-ms, any news yet when we can expect the Jumpstart HCI to work again? Thanks!

Hi @Fberson, yes we are targeting release for this month. I know many people are waiting on this release and we are working to make sure that the experience is as smooth as possible, especially considering the new capabilities around cloud deployment. We appreciate your patience!
