### ISSUE TITLE
Arc HCI Jumpstart - Azure Developer CLI 23H2 -- rdpPort parameter in bootstrap missing argument

### ISSUE THREAD

**Issue by Arnth** [microsoft/azure_arc#2407]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
https://arcjumpstart.com/azure_jumpstart_hcibox/deployment_azd

**Describe the issue or the bug**

Deployment Error Details:
VMExtensionProvisioningError: VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: 'Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.15\Downloads\0\Bootstrap.ps1 : Missing an argument
for parameter 'rdpPort'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo          : InvalidArgument: (:) [B...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)'. More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.

TraceID: 4e45b064c1888f9863d9b341e6ecf2a9

**To Reproduce**
Run azd init, azd up
Azure Region: EastUS

**Expected behavior**
I expect the deployment to continue as detailed in the guide.

**Environment summary**
Running from Windows 11 via VSCode on Powershell v7.3.11 with Azure Developer CLI 1.5.1

**Have you looked at the Troubleshooting and Logs section?**
No logs written to the HCIClient

I'm hopeful this is something small or silly that I've missed on my part.

**Comment by dkirby-ms** [comment]
I ran a fresh azd init and azd up and could not reproduce this directly. 
Can you check your (hidden) .azure/project/.env file and see if you have a value for JS_RDP_PORT?

**Comment by dkirby-ms** [comment]
Any update @Arnth?

**Comment by Arnth** [comment]
Hi Dale, sorry for the delay! Testing this out took a backseat to other work.  But, wow, yeah, the .env file was missing a value in JS_RPD_PORT.  I'll update that and try again later.  Did I miss something from the docs where I was supposed to have updated that field?

**Comment by dkirby-ms** [comment]
What may have happened is that when prompted for the RDP port instead of just hitting enter, something else was inadvertently entered and the default value of 3389 was not injected into the environment vars. I made some changes to the preprovisioning script that I believe should account for this in the future.

**Comment by potejasw** [comment]
Hi Team, I hit the same roadblock but I am unable to continue.
From the .env file I see the below entry.
JS_RDP_PORT=3389

Error:
{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'Bootstrap' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: 'Failed to download all specified files. Exiting. Error Message: CustomScript failed to download the blob fileUri_{0} because it does not exist. Please create the blob and try again, the response code and message returned were: \"The remote server returned an error: (404) Not Found. Not Found\" (Service request ID = )'. More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot. "}
