### ISSUE TITLE
HCIBox setup script failed due to incorrect parameter name "autoUpdateClusterResource"

### ISSUE THREAD

**Issue by tetsuyasodo** [microsoft/azure_arc#2498]
**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**

https://azurearcjumpstart.io/azure_jumpstart_hcibox/deployment_az

**Describe the issue or the bug**

az deployment group create script failed due to the incorrect parameter "autoUpdateCLusterResource" merged recently.

**To Reproduce**

az command succeeded without errors.
When I modified main.parameters.json file L.32 from "autoUpdateClusterResource" to "autoUpgradeClusterResource",
the command execution succeeded.

**Environment summary**

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**

**Comment by janegilring** [comment]
@tetsuyasodo Thanks for reporting this. There was [two commits](https://github.com/microsoft/azure_arc/commits/main/azure_jumpstart_hcibox/bicep/main.bicep) recently to `main.bicep`, which added new parameters:
- `autoDeployClusterResource`
- `autoUpgradeClusterResource`

Unfortunately, the sample parameters file had the wrong parameter name for one of the new parameters:
- "autoUpdateClusterResource" instead of `autoUpgradeClusterResource` as you discovered

I will go ahead and add a new PR for resolving this.
