### ISSUE TITLE
HCIBox-Client VM - Infrastructure deployment 

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/azure_arc#2730]
I've started the HCIBox-Client VM - Infrastructure deployment and I see the following information:

AzSHOST1: Extension AzureEdgeTelemetryAndDiagnostics is in place and provisioned.
Extension AzureEdgeDeviceManagement is missing
AzSHOST1: Extension AzureEdgeLifecycleManager is missing
AzSHOST1: Waiting for extension installation to complete, sleeping for 2 minutes. Attempt 13 of 90
Current state: Succeeded

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
HCIBox

For the deployment of HCIBox I choose SwedenCentral because of getting an error when trying to deploy this in eastus.

![image](https://github.com/user-attachments/assets/1f0f522b-98ed-4197-a7db-5366a9cb033f)

**Describe the issue or the bug**
Is it normal that these extensions are missing? How can I troubleshoot this?

**Comment by stefanstranger** [comment]
Seem similar to: https://github.com/microsoft/azure_arc/issues/2614

How to resolve is still a bit unclear to me.

**Comment by janegilring** [comment]
@stefanstranger I believe the issue is related to the fact that Sweden Central is not supported for Azure Stack HCI.

> Azure regions: Azure Stack HCI is supported for the following regions:
> 
> East US
> West Europe
> Australia East
> Southeast Asia
> India Central
> Canada Central
> Japan East
> South Central US

As a possible enhancement, we can look into supplying a separate parameter for what region to register HCI against to make it possible to deploy the HCIBox Client VM to a different region than the HCI cluster & nodes registers against.

However, for now I would advise to leverage one of the above regions - as the current HCIBox automation registers the HCI cluster in the same region as the location specified for the deployment.

If you have time and would like to contribute, adding a separate parameter for the HCI cluster & node registration location would be a great first contribution to HCIBox.

**Comment by stefanstranger** [comment]
Hi @janegilring sure thing. I can try to contribute to get swedencentral being added. Let me figure out what needs to change.
