### ISSUE TITLE
protect DBs with service mesh (internal / external traffic)

### ISSUE THREAD

**Issue by katomel4** [microsoft/azure_arc#306]
all external traffic to DBs and dashboard goes through LoadBalancer service (port forward).
in addition there is no mechanism to secure internal cluster communication.
it would be nice to considering at some best practice for istio:
1. ingress gateway to secure external traffic to DBs and dasboard
- tls (ssl) 
- jwt to secure aceess the dashboard via Azure AD

2. service to service authentication / authorization to the DBs instances
3. please gives scenario to protect behind azure front door WAF policy.

The AKS NSG is added with a rule to poen 1433 from external traffic. should be blocked behind ingress.
![image](https://user-images.githubusercontent.com/25114909/102695717-c15f2180-4231-11eb-96a4-cb296f5f7a26.png)

**Comment by twright-msft** [comment]
You can use the --no-external-endpoint parameter to prevent creating the external-facing endpoint:
https://docs.microsoft.com/en-us/sql/azdata/reference/reference-azdata-arc-sql-mi?toc=%2Fazure%2Fazure-arc%2Fdata%2Ftoc.json&bc=%2Fazure%2Fazure-arc%2Fdata%2Fbreadcrumb%2Ftoc.json&view=sql-server-ver15#--no-external-endpoint

Service-to-service communication can happen using the cluster IP/DNS name within the Kubernetes cluster.

We will be adding support for AD authentication to the SQL instances in the next few months.  

We also plan to allow for configuration of the various authentication options supported by Grafana/Kibana instead of only supporting the single basic auth user model that is there today.

Does this meet your requirements or is there something else we should consider?

I am not sure I understand the part in your message about "please gives scenario to protect behind azure front door WAF policy".  Can you please explain more @katomel4 ?

**Comment by likamrat** [comment]
@katomel4 any additional insights from your side?
