### ISSUE TITLE
Files and directories missing from eks/terrform

### ISSUE THREAD

**Issue by chrisadkin** [microsoft/azure_arc#316]
**Describe the bug**
The client.tf file is till missing from: https://github.com/microsoft/azure_arc/tree/main/azure_arc_k8s_jumpstart/eks/terraform

also I believe that there should be a scripts directory under the terraform directory containing some .ps1 files.

**Comment by likamrat** [comment]
@chrisadkin this scenario does not have a client vm, only the data services eks one.

**Comment by chrisadkin** [comment]
@likamrat I'm using the instructions from https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_dc_vanilla_terraform/ , these seem to imply that you should get a client VM, the graphic immediately after the bullet point:

"Copy the downloaded pem file to where the terraform binaries are located (in your cloned repository directory)."

refers to the client.tf, the same graphic seems to imply that there should be example and scripts sub directories under: eks/terraform.

**Comment by chrisadkin** [comment]
@likamrat 
![image](https://user-images.githubusercontent.com/15145995/103042975-42405500-4573-11eb-9cb3-c95d4f795779.png)

**Comment by likamrat** [comment]
The link you mentioned when opening the issue is for "Azure Arc enabled **Kubernetes**" scenario and **does not have** a client vm.
https://github.com/microsoft/azure_arc/tree/main/azure_arc_k8s_jumpstart/eks/terraform

The one you mentioned after is from "Deploy an Azure Arc Data Controller Vanilla Deployment on EKS using Terraform" scenarios which **does have** a client vm and is under the "Azure Arc enabled **data services**" scenario.

So, I think you are trying to do the "Deploy an Azure Arc Data Controller Vanilla Deployment on EKS using Terraform" scenario but not from the right directory.

Make sense?

**Comment by chrisadkin** [comment]
Ok, got it.
