### ISSUE TITLE
SQL Managed Instance ARM Template

### ISSUE THREAD

**Issue by sqlgirl3** [microsoft/azure_arc#361]
**Scenario which you are working on**

SCENARIO : Deploy an Azure SQL Managed Instance Deployment on AKS using an ARM Template

**Describe the bug**

- The deployment finished without error but when the Logon script finished and I launch the Azure Data Studio, the Azure Arc Controller is not registered and when I try to add it I recieve the following error : "Could not connect to controller https://20.73.68.124:30080. Microsoft Privacy statement and Azure Data CLI license terms have not been accepted. Execute the command: [Azure Data CLI: Accept EULA](command:azdata.acceptEula) to accept EULA to enable the features that requires Azure Data CLI."

- And in the Azure Portal , in the "SQL Managed Instance - Azure Arc" , the MI is not there. Is it normal ?

So to resume : 
- Unable to see or to register the Controler in Azure Data Studio

- in the "SQL Managed Instance - Azure Arc" , the MI is not there.

**To Reproduce**

1. Execute the deplyment command : 
az deployment group create --resource-group arc_aks_migr --name arcdatasqlmidemo --template-uri https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_data_jumpstart/aks/arm_template/mssql_mi/azuredeploy.json   --parameters azuredeploy.parameters.json

2. See error in Azure Data Studio and in the Azure Portal , The SQL Managed Instance - Azure Arc" , the MI is not there.

(Note That I can connect to the MI with Azure Data Studio and I well see the Database)

**Expected behavior**

- See the Azure Data COntroler in Azure Data Studio
- See the SQL MI in the Azure Portal , in the "SQL Managed Instance - Azure Arc"  window

**Screenshots**

**Additional context**

Thank you

**Comment by likamrat** [comment]
Thank you @sqlgirl3. Few comments here:

1. In the first time Azure Data Studio will open, you need to accept the EULA
![SNAG-0199](https://user-images.githubusercontent.com/46730876/105052394-afd18b00-5a24-11eb-9c99-646ed5ded1d8.png)

2. Currently, this is a manual step but we will automate this in the future. This is by design.

3. Since Azure Arc enabled data services is still in preview, we still don't have some functionalities automated as part of the Jumpstart scenarios. For now, managing the SQL instance via the Azure portal requires manual steps which are documented in our official docs. 
https://docs.microsoft.com/en-us/azure/azure-arc/data/monitoring-log-analytics-azure-portal-managed-instance

**Comment by sqlgirl3** [comment]
Oh thank you for the clarification. I closed the Azure Data Studio windows to quickly and I missed the EULA button. 
For MI deployment, OK I will do it manualy.

I would like to thank you for both scenarios (SQL Server & AKS/MI) of the jumpstart

**Comment by sqlgirl3** [comment]
@

**Comment by AlexanderTodorovic** [comment]
@sqlgirl3 Could you please be so kind and post the command here that you executed manually?
