### ISSUE TITLE
Azure Arc supports any recovery of failed deployment which updated db

### ISSUE THREAD

**Issue by vinupatil2008** [microsoft/azure_arc#554]
**Scenario:**
Application code and CI-CD is outside of azure (on-Prem)
After CI-CD I'm pushing built application image to Azure Image Registry.
Helm charts is doing deployments  as per namespace (Azure Kubernetes Cluster), in the helm multiple stages present with single deployment. (multiple stages of sync, in a single deployment 6 stages- each stage upgrades kubernetes resources).
Within this stages im dealing with database schemas ( Azure SQL Server DB) and Persistent storage too.

**Question:** 
In case of new image comes up and Azure Arc is syncing the change with deployment and for some reason helm deployment fails and there already some changes done at schema/ storage?

What are the options available for self healing / resolving such failures / rollback mechanism for configuration + database changes?

**Comment by likamrat** [comment]
Hi @vinupatil2008 , I am not sure I fully understand the Q but when it comes to Azure Arc, by having a GitOps configuration that points to your application git repo, you will be able to (potentially) roll back to the previous config. I say "potentially" because I don't completely understand the entire flow of the deployment. 

As for the database, I highly recommend reading [this great article](https://www.weave.works/blog/how-to-correctly-handle-db-schemas-during-kubernetes-rollouts) from Weaveworks around how to correctly handle DB schemas during Kubernetes rollouts.

**Comment by likamrat** [comment]
@vinupatil2008 I will go ahead and close this for now. Feel free to reach out for anything else.

**Comment by vinupatil2008** [comment]
> Hi @vinupatil2008 , I am not sure I fully understand the Q but when it comes to Azure Arc, by having a GitOps configuration that points to your application git repo, you will be able to (potentially) roll back to the previous config. I say "potentially" because I don't completely understand the entire flow of the deployment.
> 
> As for the database, I highly recommend reading [this great article](https://www.weave.works/blog/how-to-correctly-handle-db-schemas-during-kubernetes-rollouts) from Weaveworks around how to correctly handle DB schemas during Kubernetes rollouts.

Thank you

> @vinupatil2008 I will go ahead and close this for now. Feel free to reach out for anything else.

Thank you Kamrat.
Article you shared is good information, it cleared out many things.
