### ISSUE TITLE
PostgreSQL Hyperscale Deployment on EKS - data controller deployment failure

### ISSUE THREAD

**Issue by ischepin** [microsoft/azure_arc#743]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_postgres_hs_terraform/

**Describe the bug**
At "Windows Login & Post Deployment" stage when script is running inside windows client machine there is an error during deployment of Azure data controller:
`
{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'dataController' is not valid according to the validation procedure. The tracking id is '1dd0e5aa-a47e-49a4-86dd-1cb8918d35d2'. See inner errors for details.","details":[{"code":"OpenAPISpecValidationFailedForTemplateDeploymentResources","message":"One or more resources in template deployment preflight validation request failed during OpenApi spec (swagger) validation. Please check error details for the resource identifiers.","details":[{"code":"HttpRequestPayloadAPISpecValidationFailed","target":"/subscriptions/a088ac12-28e0-48d5-a00d-9f5d48c7cfbb/resourceGroups/RG/providers/Microsoft.AzureArcData/dataControllers/jumpstart-dc","message":"HTTP request payload failed validation against API specification with one or more errors. Please see details for more information.","details":[{"code":"InvalidFormat","message":"Object didn't pass validation for format uuid: . Paths in payload: '$.properties.logAnalyticsWorkspaceConfig.workspaceId'"}]}]}]}}
`
As a result, data controller is not deployed and script waits for it indefinitely. I tried the entire scenario from scratch and got the same error.

**To Reproduce**
1. Follow steps from "Deploy an Azure PostgreSQL Hyperscale Deployment on EKS using Terraform" scenario

**Expected behavior**
Data controller is deployed

**Script output**
[arc.txt](https://github.com/microsoft/azure_arc/files/7106457/arc.txt)

**Comment by dkirby-ms** [comment]
Thanks @ischepin. 

It looks like this scenario doesnt have the same guidance to show how to create the user and attach correct permissions. In the Azure Arc-enabled servers AWS scenarios we do show this, so we should mirror our approach from those scenarios in the AWS data services scenarios. 

I also notice that we have the same missing explanation in the EKS kubernetes-only scenario.

**Comment by mdrakiburrahman** [comment]
Thanks for flagging this @ischepin - I was able to repro the issue.

This PR should fix it: https://github.com/microsoft/azure_arc/pull/744 - I've validated on EKS.

The issue was ARM added an extra layer of validation in to check for Log Analytics WS Params - which weren't being passed in via Terraform.

You have 2 options to proceed with the scenario:
1. Wait for the PR to get merged. Tear down your existing env, refresh your fork from `main`
2. Look at [the PR](https://github.com/microsoft/azure_arc/pull/744/files#diff-9fa3cdfc2831cda2b3aa8af799726692b49880270933e58ca7d7cff3a718d628R161) - in your existing env, run the cli commands from the PR to deploy the WS. Replace the DC deployment ARM templates from `main`, run this [portion](https://github.com/microsoft/azure_arc/blob/a2a62c3430c6c6bce2821d7336f15a0943896e1a/azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1#L174) to update the placeholder in the ARM templates. Redeploy the DC ARM templates, and you should be able to deploy Postgres after that.

I'm going to keep the issue open until the PR is merged in.
