### ISSUE TITLE
Azure Arc enabled data services for EKS : logon script does not end

### ISSUE THREAD

**Issue by dineshkvp** [microsoft/azure_arc#746]
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/eks/eks_mssql_mi/

I am trying to setup Amazon Elastic Kubernetes Service and SQL Managed Instance using Terraform through the referenced jump start tutorial (azure_arc\azure_arc_data_jumpstart\eks\mssql_mi\terraform)

I got the below error while running the logon script in Windows client instance

Waiting for bootstrapper pod, hold tight...
No resources found in arc namespace.
Waiting for bootstrapper pod, hold tight...
Waiting for bootstrapper pod, hold tight...
Waiting for bootstrapper pod, hold tight...
Waiting for bootstrapper pod, hold tight...
WARNING: Command group 'k8s-extension' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command requires the extension customlocation. It will be installed first.
The installed extension 'customlocation' is in preview.
Command group 'customlocation' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Deployment failed. Correlation ID: 2568c5dd-ae97-48fd-94bc-173229339592. "Microsoft.ExtendedLocation" resource provider does not have the required permissions to create a namespace on the cluster. Refer to https://aka.ms/ArcK8sCustomLocationsDocsEnableFeature to provide the required permissions to the resource provider.
Create Azure Monitor for containers Kubernetes extension instance

and after few steps, it stays repeating with below comments

No resources found in arc namespace.
Waiting for data controller. Hold tight, this might take a few minutes...

I tried enabling custom-locations with the below command

az connectedk8s enable-features -n NousEKSCluster -g Azure_Arc_Data_Rg --features cluster-connect custom-locations

but i get the error
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Ensure that you have the latest helm version installed before proceeding.
This operation might take a while...

Problem loading the kubeconfig file.Invalid kube-config file. No configuration found.

The following is the screen shot of my RG
![error-rg](https://user-images.githubusercontent.com/5206595/132686366-cb002bed-de9b-4850-b1cd-7b33cba39ae1.png)
![error1](https://user-images.githubusercontent.com/5206595/132686755-39a42e86-4ad6-401d-948d-d4c12f0192b6.png)

**Comment by mdrakiburrahman** [comment]
@dineshkvp - thanks for reaching out. We're not able to reproduce the issue in a net new AWS sandbox env deployment.

From your screenshots, I see the `bootstrapper` pod was deployed, and the Data Controller deployment was submitted to ARM, but I'm not seeing the `control-xxxx` and `controldb-0` pods for the Data Controller get spun up - this is supposed to happen immediately after the ARM deployment, if the `bootstrapper` was successfully able to apply the Data Controller pre-reqs (secrets, CRDs etc) against your EKS cluster. 

This, and the fact that you're not able to load the `kubeconfig` file, may indicate there might be some AWS environment-specific restriction in your EKS cluster that is preventing certain pre-reqs for the `control` pods to get created.

Since we aren't able to repro - we need further data points beyond the screenshots to meaningfully assist you here why things aren't working in your AWS env:
1. Are you doing this deployment in a Corporate AWS environment? Or do you have full Admin permissions in this environment?
2. Please upload the `C:\Temp\DataServicesLogonScript.log` here - you may have to go through the file and wipe and sensitive info such as SubId and SPId etc.
3. Please share logs from bootstrapper pod: `kubectl logs bootstrapper-2wc9m-n arc`
4. Run describe command against pod for events `kubectl describe pod bootstrapper-2wc9m -n arc`
5. What do you see when you navigate to Deployments for the datacontroller?
![image](https://user-images.githubusercontent.com/46581776/132987782-3d54838d-4ae2-4b8d-8968-70795f988662.png)

If you aren't seeing succeeded, could you please upload detailed screenshots and logs from ARM? You will have to click inside the `dataController` Deployment Hyperlink above.
6. What do you see when you run `kubectl describe secret controller-login-secret -n arc`? 
7. What do you see when you run `kubectl get secrets -n arc`?  Are you seeing these?
![image](https://user-images.githubusercontent.com/46581776/132988119-75021caa-e804-48e6-abe2-f68d11907d70.png)
8. What do you see when you run `kubectl get crd -n arc`?

**Comment by dineshkvp** [comment]
@mdrakiburrahman 
Here is the list of resources
![err0](https://user-images.githubusercontent.com/5206595/133063566-da6d70f8-2c84-4fa8-9eb8-687132d0dbba.png)

Please find the log file
[DataServicesLogonScript - Copy.log](https://github.com/microsoft/azure_arc/files/7153168/DataServicesLogonScript.-.Copy.log)

1.	Are you doing this deployment in a Corporate AWS environment? Or do you have full Admin permissions in this environment?
Yes, I do in corporate AWS environment. I have full admin permissions in the environment.

2.	Please upload the C:\Temp\DataServicesLogonScript.log here - you may have to go through the file and wipe and sensitive info such as SubId and SPId etc.
  Done

3.	Please share logs from bootstrapper pod: kubectl logs bootstrapper-mc29m -n arc

![err1](https://user-images.githubusercontent.com/5206595/133061335-da576a4b-db6d-4dcf-bbb6-842ffc6e532f.png)

4.	Run describe command against pod for events kubectl describe pod bootstrapper-mc29m -n arc
![err2](https://user-images.githubusercontent.com/5206595/133061822-e5f9b162-8805-48df-a23a-0ab840239a2e.png)

5.	What do you see when you navigate to Deployments for the datacontroller?

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Forbidden","message":"secrets \"controller-login-secret\" is forbidden: User \"581ce62d-cf79-475e-92a1-4d9794bb2353\" cannot get resource \"secrets\" in API group \"\" in the namespace \"arc\""}]}

![err3](https://user-images.githubusercontent.com/5206595/133061994-ca221a92-58cf-44d9-838d-2387126cbd27.png)

6.	What do you see when you run kubectl describe secret controller-login-secret -n arc?

![err4](https://user-images.githubusercontent.com/5206595/133062471-e4c376c3-5892-429d-a051-037d660dc86d.png)

7.	What do you see when you run kubectl get secrets -n arc? 

![err5](https://user-images.githubusercontent.com/5206595/133062788-dfaae217-a9db-4d9b-9a21-a17491dc056a.png)

8. What do you see when you run kubectl get crd -n arc?
![err6](https://user-images.githubusercontent.com/5206595/133063169-f2a22253-3817-455a-9fe4-94015c3747fa.png)

Hope these details will help you to help me.

**Comment by mdrakiburrahman** [comment]
@dineshkvp - the issue is with this error:
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Forbidden","message":"secrets "controller-login-secret" is forbidden: User "**581ce62d-cf79-475e-92a1-4d9794bb2353**" cannot get resource "secrets" in API group "" in the namespace "arc""}]}`

I also realized you had opened this exact same issue in August: https://github.com/microsoft/azure_arc/issues/711

The fact that you ran into this issue twice - and we're not able to reproduce on either instances with net new deployments implies that the issue is likely not related to the Jumpstart Automation (i.e. this repo) - but perhaps something specific to your AWS environment.

The last time you ran into this issue, we shared evidence that it might be related to the AWS IAM Role - see here: https://github.com/microsoft/azure_arc/issues/711#issuecomment-894814533

Without debugging live in your specific environment - we can't really comment on what could be causing this. The right support channel for this would be to raise an Azure Support Ticket - one of the CSS engineers would be able to debug this live with you. When you are able to learn what the root cause is after the investigation - please share back with us here - and we'd be happy to update our docs with any important callouts.

Additionally, if you're just looking to play around/learn Arc - you could also try the deployment on AKS where you probably won't hit this error. The learning experience will be identical - and if you keep both envs up, you might actually find the differences between your AKS (working), and EKS (not-working) environment to naturally resolve the issue yourself.
