### ISSUE TITLE
k3s Azure ARM template - hardcoded iod

### ISSUE THREAD

**Issue by jjindrich** [microsoft/azure_arc#785]
Hi, I'm using this jumpstart to deploy Azure Arc on K3s. There is a bug with custom location. There is hardcoded oid in this template https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json with script https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/istall_k3s.sh

There is hardcoded --custom-locations-oid '51dfe1e8-70c6-4de5-a08e-e18aff23d815'

There problem is that you cannot run creating custom location which is required by App Services https://docs.microsoft.com/en-us/Azure/app-service/manage-create-arc-environment?tabs=bash#create-a-custom-location

Please remove this hardcoded oid

**Comment by jjindrich** [comment]
Hi, I think this is not right fix. You only deleted oid but there is critical warning. You have to load OID for Custom Locations RP az ad sp show --id 'bc313c14-388c-4e7d-a58e-70017303ee3b' --query objectId -o tsv.
And this objectId send to az connectedk8s connect

**Comment by likamrat** [comment]
Thank you @jjindrich. I understand. So, a couple of things here:

- I added the _`--kube-config`_ flag to the connect command. You can see this on [this branch](https://github.com/microsoft/azure_arc/blob/oid_fix/azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/install_k3s.sh#L52). As you can see, deployment was successful.

![image](https://user-images.githubusercontent.com/46730876/135863173-4c10b117-d804-4585-974c-1552a64cee71.png)

![image](https://user-images.githubusercontent.com/46730876/135863262-33915d2d-e8b4-4cf7-84a0-7677e13ba758.png)

- I would like you the check #765 and better understand the direction we are heading with this fix. We actually already implemented it for ArcBox in #778. The most important thing here is to understand why we missed it and this is because of we (and you) were developing against our Microsoft subscription and as a result, hardcoding the oid but as you can see, this is a problem. 

- The mitigation to that is to use the _`--kube-config`_ flag in the connect command AND when deploying a Custom Location, using the _`--kubeconfig`_ like we have in the #778
